---
operators: [["+",2],["-",2],["*",2],["/",2]]
max_initial_depth: 6
population_size: 100
max_generation: 20
tournament_size: 5
elitism_size: 1
max_depth: 17
verbose: True
threads: 1
model_name: "SimpleThresholdClassifier"
fitnessType: "WAF"