---
OPERATORS: [("+",2),("-",2),("*",2),("/",2)]
MAX_DEPTH: 6
POPULATION_SIZE: 100
MAX_GENERATION: 20
TOURNAMENT_SIZE: 5
ELITISM_SIZE: 1
LIMIT_DEPTH: 17
VERBOSE: True
THREADS: 5
MODEL_NAME: "SimpleThresholdClassifier"
FITNESS_TYPE: "WAF"